const products = [
  {
    id: '1a',
    name: 'Jacob & Co',
    image: 'https://image.dynamixse.com/fit/400x500/webp.png-lossy-85.q80/https://dynamix-cdn.s3.amazonaws.com/jacobandcocom/jacobandcocom_801175632.png',
    description: 'Кварцевые часы. Особая конструкция, устойчивая к пыли и загрязнениям, защищает от ударов и вибрации. Часы оснащены технологией Bluetooth. Двойная электролюминесцентная подсветка. Неоновое покрытие. Встроенный цифровой компас. Альтиметр до 10 000 м. Память данных альтиметра (до 40 записей о высотных точках рельефа местности). График набора высоты. Барометр (260 / 1.100 hPa). Термометр (-10°C / +60°C). Шагомер. Данные о восходе/закате солнца. Функция мирового времени.',
    brand: 'Casio',
    category: 'Watch',
    price: 39990,
    countInStock: 3,
    rating: 5,
    numReviews: 3,
  },
  {
    id: '2b',
    name: 'Patek Philippe',
    image: 'https://i.pinimg.com/originals/c6/91/3b/c6913bb6a6a16228b4ddd53bdd1c6f8d.png',
    description: 'Стильные швейцарские часы с надежным массивным корпусом и потрясающей водозащитой, позволяющей совершать глубоководные погружения. Мужские механические часы с автоподзаводом. Надежный швейцарский механизм ETA 2824-2. Центральные часовая, минутная и секундная стрелки. Апертура даты в позиции 3 часов. Черный циферблат. Керамический безель.',
    brand: 'Swiss',
    category: 'Watch',
    price: 49990,
    countInStock: 3,
    rating: 3.5,
    numReviews: 4,
  },
  {
    id: '3c',
    name: 'Rolex Pepsi ',
    image: 'https://www.pngkey.com/png/full/903-9033267_rolex-gmt-master-ii-18k-white-gold-pepsi.png',
    description: 'Мужские механические часы с автоподзаводом. Калибр 4694. Водостойкость WR 200. Центральные часовая, минутная и секундная стрелки. Индикация даты и дня недели на позиции трех часов. Стрелки и метки с люминесцентным покрытием. Корпус выполнен из полированной нержавеющей стали.',
    brand: 'Orient',
    category: 'Watch',
    price: 21000,
    countInStock: 2,
    rating: 2.5,
    numReviews: 3,
  },
  {
    id: '4d',
    name: 'Bulova Curv',
    image: 'https://embed.widencdn.net/img/citizenwatch/bmmynfxl8q/340x510px/CURV.png?u=41zuoe&keep=c&crop=false',
    description: 'Высокоточные элегантные часы с изогнутым корпусом, повторяющим линию изгиба запястья. Кварцевый хронограф. Первый в мире хронограф с изогнутым механизмом с частотой колебаний 262 кГц, что превышает стандарт в 8 раз, для высокой точности. Корпус выполнен из титана и нержавеющей стали. Каучуковый ремень. Сапфировое стекло. Диаметр 44мм. Водозащита 30м.',
    brand: 'Bulova',
    category: 'Watch',
    price: 57310,
    countInStock: 2,
    rating: 5,
    numReviews: 5,
  },
  {
    id: '5e',
    name: 'Loginess',
    image: 'https://cdn.shopify.com/s/files/1/0506/8037/products/L2.673.4.78.3_1024x1024.png?v=1578361500',
    description: 'Кварцевые часы. Солнечная батарея. Калибр 8X22. Водостойкость WR 100. Часы, минуты, секунды, дата. Люминесцентные стрелки и метки. Встроенный GPS модуль для корректировки часового пояса и точного времени. Индикатор заряда. Режим летнего времени. Режим - в полете. Корпус выполнен из нержавеющей стали. Диаметр корпуса 45 мм. Сапфировое стекло с супер-прозрачным покрытием. Стальной браслет с раскладывающейся застежкой.',
    brand: 'Seiko',
    category: 'Watch',
    price: 90750,
    countInStock: 2,
    rating: 4.5,
    numReviews: 6,
  },
  {
    id: '6f',
    name: 'Breguet',
    image: 'https://www.breguet.com/sites/default/files/gardetemps/variante/soldat_png/7097bbg19wu.png',
    description: 'Стрелки и часовые метки имеют покрытие LumiBrite. Циферблат синего цвета. Однонаправлено вращающийся безель. Круглый корпус выполнен из полированной нержавеющей стали с черным PVD покрытием. Диаметр корпуса составляет 44 мм, толщина 14 мм. Завинчивающаяся заводная головка с защитой. Стальной браслет с тройной раскладывающейся застежкой и дополнительным фиксатором. Закаленное минеральное стекло повышенной прочности Hardlex с антибликовым покрытием устойчиво к мелким механическим повреждениям.',
    brand: 'Seiko',
    category: 'watch',
    price: 37500,
    countInStock: 0,
    rating: 4,
    numReviews: 9,
  },
  {
    id: '7g',
    name: 'Ferrari',
    image: 'https://www.hublot.com/sites/default/files/styles/watch_item_desktop_1x_scale_no_crop_600_6000_/public/techframe-ferrari-tourbillon-chronograph-sapphire-white-gold-45-mm-408.JW.0123.RX-soldier-shot.png?itok=scmZg_st',
    description: 'Мужской кварцевый хронограф. Калибр 8T63. Часы, минуты, секунды. Индикация даты. Корпус и браслет выполнены из нержавеющей стали с черным PVD покрытием. Диаметр корпуса 44 мм, толщина 11 мм. Заводная головка с защитой. Минеральное стекло повышенной прочности Hardlex. Завинчивающаяся задняя крышка. Водостойкость WR 100.',
    brand: 'Seiko',
    category: 'watch',
    price: 27500,
    countInStock: 8,
    rating: 3.5,
    numReviews: 2,
  },
  {
    id: '7g',
    name: 'Hublot',
    image: 'https://www.hublot.com/sites/default/files/styles/watch_item_desktop_1x_scale_no_crop_600_6000_/public/2020-09/big-bang-ferrari-white-gold-1000gp-soldier2.png?itok=0N9kSiQR',
    description: 'Мужской кварцевый хронограф. Калибр 8T63. Часы, минуты, секунды. Индикация даты. Корпус и браслет выполнены из нержавеющей стали с черным PVD покрытием. Диаметр корпуса 44 мм, толщина 11 мм. Заводная головка с защитой. Минеральное стекло повышенной прочности Hardlex. Завинчивающаяся задняя крышка. Водостойкость WR 100.',
    brand: 'Seiko',
    category: 'watch',
    price: 27500,
    countInStock: 8,
    rating: 3.5,
    numReviews: 2,
  }
]

export default products